version: "3.9"

services:
  api:
    build: .
    container_name: athena_back
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - athena:/app/uploads
    env_file:
      - .env
    restart: always
    networks:
      - red_puente

volumes:
  athena:
    external: true

networks:
  red_puente:
    name: athena_global_net
    external: true