version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_app_basic_lms
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: always